# Generated by Django 3.0.8 on 2020-07-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=20)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('temperature', models.FloatField()),
                ('temp_feels_like', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.FloatField()),
                ('cloud_counter', models.IntegerField()),
            ],
        ),
    ]
