# Generated by Django 3.0.8 on 2020-08-01 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('flag', models.CharField(max_length=512)),
                ('wiki_page', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Country')),
            ],
            options={
                'unique_together': {('longitude', 'latitude')},
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=20)),
                ('temp_feels_like', models.CharField(max_length=20)),
                ('temp_min', models.CharField(max_length=20)),
                ('temp_max', models.CharField(max_length=20)),
                ('pressure', models.CharField(max_length=20)),
                ('humidity', models.CharField(max_length=20)),
                ('visibility', models.CharField(max_length=20)),
                ('wind_speed', models.CharField(max_length=20)),
                ('wind_deg', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.ManyToManyField(to='weather.Location')),
            ],
        ),
    ]
