# Generated by Django 3.0.8 on 2020-08-01 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20200801_1934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forecast',
            new_name='Weather',
        ),
    ]
