# Generated by Django 3.0.8 on 2020-08-02 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20200801_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.Country'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.Location'),
        ),
    ]
