# Generated by Django 3.0.8 on 2020-08-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20200802_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
