# Generated by Django 3.0.8 on 2020-08-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_auto_20200802_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
