# Generated by Django 3.0.8 on 2020-08-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_auto_20200802_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='location',
        ),
    ]
