# Generated by Django 3.0.8 on 2020-08-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_remove_weather_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
